#配置服务端口
server:
  port: 8000
spring:
  profiles:
    active: dev
  #配置登录账号密码
  security:
    user:
      name: guest
      password: 9879871221
  rabbitmq:
    host: 203.195.224.186
    port: 5673
    username: guest
    password: 9879871221
eureka:
  client:
    #指定服务注册中心地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    #是否从注册中心获取注册的服务
    fetch-registry: false
    #是否注册到注册中心
    register-with-eureka: false
  server:
    #注册中心的保护机制
    enable-self-preservation: false
  instance:
    #使用主机名来定义注册中心的地址
    prefer-ip-address: true
    #服务地址
    hostname: 127.0.0.1
management:
  security:
     enabled: false
---
spring:
  profiles: pro
  security:
    user:
      name: ppp
---
spring:
  profiles: dev
  security:
    user:
      name: ttt