#配置服务端口
server:
  port: 8777
spring:
  profiles:
    active: pro
  #配置登录账号密码
  security:
    user:
      name: guest
      password: 9879871221
eureka:
  client:
    #指定服务注册中心地址
    service-url:
      defaultZone: http://guest:9879871221@${eureka.instance.hostname}:8000/eureka
  instance:
    #使用主机名来定义注册中心的地址
    prefer-ip-address: true
    #服务地址
    hostname: 127.0.0.1
---
spring:
  profiles: pro
  application:
    name: Client-PRO
---
spring:
  profiles: dev
  application:
    name: Client-DEV666
